/**
 * 在这里写一些常量，如果常量多的话再进行拆分
 * Created by WebStorm.
 * User: liulin
 * Date: 2018/5/13
 * Time: 下午5:40
 */

const ARTICLE_PAGINATION = 10
const ARTICLE_COMMENT_PAGINATION = 10
const ARTICLE_CHILDREN_COMMENT_PAGINATION = 10

let CONSTS = {
  ARTICLE_PAGINATION,
  ARTICLE_COMMENT_PAGINATION,
  ARTICLE_CHILDREN_COMMENT_PAGINATION
}
export default CONSTS
